name: comfort_crash
description: "A new Flutter project."

# Prevent publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase / Core
  base_core: ^1.2.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6

  # State Management
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0

  # AI
  google_generative_ai: ^0.2.0

  # Storage
  shared_preferences: ^2.2.2

  # Animations
  rive: ^0.11.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Where you put your downloaded .riv and .json files
  assets:
    - assets/animations/coin_toss.riv
    - assets/animations/pond_ripple.riv
    - assets/animations/coin_toss.json
    - assets/animations/pond_ripple.json
